theme: jekyll-theme-minimal
title: Hour of Code @ WIT
description: A holding page for WIT's participation in Hour of Code activities
logo: https://github.com/curlybert/hourofcodewit/blob/master/WIT_Logo.png
